Fused build and check safe to build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,18 +3,38 @@ on:
   push:
     branches:
       - main
-  workflow_run:
-    workflows: [ "Check safe to build" ]
-    types:
-      - completed
+  pull_request_target:
+    branches:
+      - main
   workflow_dispatch:
 
 jobs:
   build:
-
     name: Build
     runs-on: ubuntu-latest
     steps:
+      - name: Check if organization member
+        id: is_organization_member
+        uses: JamesSingleton/is-organization-member@1.0.0
+        with:
+          organization: Giskard-AI
+          username: ${{ github.actor }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Ask to add the 'safe for build' label
+        if: ${{ github.actor != 'dependabot[bot]' && !contains(github.event.*.labels.*.name, 'safe for build') && steps.is_organization_member.outputs.result == 'false' }}
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |
+            Please add the 'safe for build' label in order to perform the sonar analysis!
+
+      - name: Interrupt job
+        if: ${{ github.actor != 'dependabot[bot]' && !contains(github.event.*.labels.*.name, 'safe for build') && steps.is_organization_member.outputs.result == 'false' }}
+        shell: bash
+        run: |
+          echo "Job failed due to user not being a member of Giskard-AI organization and the 'safe for build' label not being set on the PR"
+          exit 1
+
       - name: Stop on security check failure
         if: ${{ github.event.workflow_run.conclusion == 'failure' }}
         shell: bash
